name: Build Dostup_YT_DS_RBLX

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd myzapretui
        pip install -r requirements.txt
        pip install pyinstaller

    # --- НОВЫЙ ШАГ: Внедрение секрета ---
    - name: Inject Secret Salt
      env:
        # Забираем секрет из настроек репозитория
        SECRET_FROM_GITHUB: ${{ secrets.MY_APP_SALT }}
      run: |
        cd myzapretui
        # Создаем файл config.py и записываем в него переменную
        echo "SECRET_SALT = '${env:SECRET_FROM_GITHUB}'" > config.py

    - name: Build with PyInstaller
      run: |
        cd myzapretui
        
        # PyInstaller автоматически подхватит свежесозданный config.py и зашьет его в exe
        pyinstaller --noconfirm --onefile --windowed `
          --add-data "..\binaries\win64\winws.exe;proxy_bin" `
          --add-data "..\*.bat;proxy_bin" `
          main.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dostup-Executable
        path: myzapretui/dist/main.exe

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dostup_YT_DS_RBLX-Exec
        path: myzapretui/dist/main.exe
